apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        ad.datadoghq.com/postgres.check_names: '["postgres"]'
        ad.datadoghq.com/postgres.init_configs: '[{}]'
        ad.datadoghq.com/postgres.instances: '[{"host": "%%host%%", "port": "%%port%%","username": "datadog","password": "datadog" }]'
    spec:
      containers:
      - name: postgres
        image: sample_postgres:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          hostPort: 5432
          name: postgresport
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - name: http
    protocol: TCP
    port: 5432
    targetPort: 5432